### ISSUE TITLE
Deploy file in the same bucket

### ISSUE THREAD

**Issue by Cafnio** [AWSinAction/lambda#1]
Hi there.

First of all thanks for the great work that you've done, really helpfull :)

Was wondering if it's possibel to change the code so that the resized bucket is the same as the original bucket (and in the same folder of the original).

Basicly I want users to upload their images (they go to different folders). After that, Lambda resized it automaticly and saves the resized images in the same place, so I don't have to change the url (only the name of the file)

Thanks

**Comment by michaelwittig** [comment]
You can change the bucket here: https://github.com/AWSinAction/lambda/blob/master/index.js#L62
and the file name here: https://github.com/AWSinAction/lambda/blob/master/index.js#L63
